### PR TITLE
Remove icons field on client

### PR DESCRIPTION
**Pull request by shadowfacts**
To prevent [this][crash] crash.

[crash]: http://pastebin.ubuntu.com/10210421/

### CODE REVIEW

**Comment by shadowfacts** [comment]
Update:
Temporary patched version [here][dl] until the pull request is merged.

[dl]: https://app.box.com/s/2gyk502digpev1gqn16uumx1mtrq9bgs

**Comment by hilburn** [comment]
Have you tested this? because I've seen this sort of thing cause far more harm than good

**Comment by shadowfacts** [comment]
Yep, tried putting StevesAddons on my server which crashed, this fixed it.

**Comment by hilburn** [comment]
that's... odd - do you run anything like cauldron or non-standard?

**Comment by shadowfacts** [comment]
Nope, just a normal Forge server

**Comment by hilburn** [comment]
I will try to hunt it down then, because that definitely shouldn't be happening - if I can't find a solution I will build with this, but I have had issues with doing that kind of thing in other projects so am wry of it causing more problems for other people

**Comment by shadowfacts** [comment]
This is necessary, the issue is caused because all of the methods in IIcon [don't exist][iicon] on a dedicated server. Anything trying to use IIcon will break.

[iicon]: http://pastebin.ubuntu.com/10211137/

**Comment by hilburn** [comment]
I am well aware of that, however, as I said, I have run into issues with @SideOnly() on fields before and would prefer not to use it

As it is, you are the only person to have reported an issue with running a server, and it works in my dev environment completely fine - this is because the only methods that access IIcon are client side only, so the server never attempts to call anything.

Regardless - I'm pushing a fix I should have used before which means it doesn't try to generate the IIcon array on the server side - should fix your issues - if it doesn't then I'll accept this PR

[Fixed Steve's Addons](https://dl.dropboxusercontent.com/u/41428129/Mods/StevesAddons-1.7.10-0.7.4.jar)

**Comment by shadowfacts** [comment]
Thank you very much :smile:, this fixed it!

**Pull request closed without merging**
